In [1]:
print("ola, mundo!")

ola, mundo!


In [3]:
import numpy as np

#Criando duas matrizes 3x3
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

In [4]:
# Soma das matrizes 
soma = A + B
print("\nSoma de A + B:")
print(soma)


Soma de A + B:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
